config/routes.rb
Rails.application.routes.draw do
  get 'users/show'

  devise_for :users
  resources :users, only: [:show]
  resources :topics do
    resources :bookmarks do
      resources :likes, only: [:create, :destroy]
    end
  end
  resources :bookmarks, only: [:index]
  root 'welcome#index'

  get 'about' => 'welcome#about'

  post :incoming, to: 'incoming#create'

end

app/models/bookmark.rb
class Bookmark < ActiveRecord::Base
  belongs_to :topic
  belongs_to :user
  has_many :likes, dependent: :destroy
end

app/models/like.rb
class Like < ActiveRecord::Base
  belongs_to :bookmark
  belongs_to :user
end

app/models/topic.rb
class Topic < ActiveRecord::Base
  belongs_to :user
  has_many :bookmarks, dependent: :destroy
  extend FriendlyId
  friendly_id :title, use: [:slugged, :history]

  def should_generate_new_friendly_id?
    title_changed?
  end  
end

app/models/user.rb
class User < ActiveRecord::Base
  # Include default devise modules. Others available are:
  # :confirmable, :lockable, :timeoutable and :omniauthable
  devise :database_authenticatable, :registerable,
         :recoverable, :rememberable, :trackable, :validatable, :confirmable

  has_many :topics, dependent: :destroy
  has_many :bookmarks, dependent: :destroy
  has_many :likes, dependent: :destroy

  def liked(bookmark)
    likes.where(bookmark_id: bookmark.id).first
  end
end

app/controllers/application_controller.rb
class ApplicationController < ActionController::Base
  # Prevent CSRF attacks by raising an exception.
  # For APIs, you may want to use :null_session instead.
  include Pundit
  protect_from_forgery with: :exception
  before_action :configure_permitted_parameters, if: :devise_controller?

  rescue_from Pundit::NotAuthorizedError, with: :user_not_authorized

  protected

    def configure_permitted_parameters
      devise_parameter_sanitizer.for(:sign_up) << :name
      devise_parameter_sanitizer.for(:account_update) << :name
    end

  private

    def user_not_authorized
      flash[:error] = 'You are only allowed to edit or delete items that you created.'
      redirect_to(request.referrer || root_path)
    end
end

app/controllers/bookmarks_controller.rb
class BookmarksController < ApplicationController
  def new
    @topic = Topic.friendly.find(params[:topic_id])
    @bookmark = Bookmark.new
  end

  def index
    @bookmarks = Bookmark.all
  end

  def create
    @topic = Topic.friendly.find(params[:topic_id])
    @bookmark = Bookmark.new( bookmark_params )
    authorize @bookmark
    @bookmark.topic = @topic
    @bookmark.user = current_user
    if @bookmark.save
      flash[:notice] = "bookmark was created."
      redirect_to @topic
    else
      flash[:error] = "There was an error saving the bookmark. Please try again."
      render :new
    end
  end

  def show
    @topic = Topic.friendly.find(params[:topic_id]) 
    @bookmark = bookmark.find(params[:id])
    authorize @bookmark
  end

  def edit
    @topic = Topic.friendly.find(params[:topic_id]) 
    @bookmark = Bookmark.find(params[:id])
    authorize @bookmark
  end

  def update
    @topic = Topic.friendly.find(params[:topic_id])
    @bookmark = Bookmark.find(params[:id])
    authorize @bookmark
    if @bookmark.update_attributes(params.require(:bookmark).permit(:url))
      flash[:notice] = "bookmark was updated."
      redirect_to @topic
    else
      flash[:error] = "There was an error saving the bookmark.  Please try again."
      render :edit
    end
  end

  def destroy
    @topic = Topic.friendly.find(params[:topic_id])    
    @bookmark = Bookmark.find(params[:id])
    authorize @bookmark
    if @bookmark.destroy
      flash[:notice] = "bookmark was deleted."
    else
      flash[:error] = "There was an error deleting the bookmark.  Please try again."
    end 
      redirect_to @topic
  end

  private

  def bookmark_params
    params.require(:bookmark).permit(:url)
  end
end

app/controllers/incoming_controller.rb
class IncomingController < ApplicationController

  skip_before_action :verify_authenticity_token, only: [:create]

  def create
    puts "INCOMING PARAMS HERE: #{params}"
    @user = User.find_by email: params[:sender]
    @topic = Topic.find_by title: params[:subject]
    @url = params["body-plain"]

    if @user.nil?
      @user = User.new(
        name: "New User",
        email: params[:sender]
      )
      @user.skip_confirmation!
      @user.save!
    end

    if @topic.nil?
      @topic = Topic.create(
        title: params[:subject]
        )
      @topic.save!
    end 

    @bookmark = Bookmark.create(
      url: @url,
      topic_id: @topic.id
      )
     @bookmark.save!

     head 200
  end
end

app/controllers/likes_controller.rb
class LikesController < ApplicationController

  def create
    @topic = Topic.friendly.find(params[:topic_id])
    @bookmark = Bookmark.find(params[:bookmark_id])
    @like = current_user.likes.build(bookmark: @bookmark)
    authorize @like
    if @like.save
      redirect_to(request.referrer || @topic)
    else
      flash[:error] = "There was an error liking the bookmark.  Please try again."
      render :new
    end
  end

  def destroy
    @topic = Topic.friendly.find(params[:topic_id])
    @bookmark = Bookmark.find(params[:bookmark_id])
    @like = current_user.liked(@bookmark)
    authorize @like
    if @like.destroy
      redirect_to(request.referrer || @topic)
    else
      flash[:error] = "There was an error un-liking the bookmark.  Please try again."
      redirect_to @topic
    end
  end
  
end

app/controllers/topics_controller.rb
class TopicsController < ApplicationController
  before_action

  def index
    @topics = Topic.all
  end

  def show
    @topic = Topic.friendly.find(params[:id])
    if request.path != topic_path(@topic)
      redirect_to @topic, status: :moved_permanently
    end
    @bookmarks = @topic.bookmarks.all
    @bookmark = Bookmark.new
  end

  def new
    @topic = Topic.new
    authorize @topic
  end

  def create
    @topic = Topic.new(topic_params)
    authorize @topic
    @topic.user = current_user
    if @topic.save
      flash[:notice] = "Topic was saved."
      redirect_to topics_path
    else
      flash[:error] = "There was an error saving the topic.  Please try again."
      render :new
    end
  end

  def edit
    @topic = Topic.friendly.find(params[:id])
    authorize @topic
  end  

  def update
    @topic = Topic.friendly.find(params[:id])
    authorize @topic
    if @topic.update_attributes(topic_params)
      flash[:notice] = "Topic was updated."
      redirect_to @topic
    else
      flash[:error] = "There was an error updating the topic.  Please try again."
      render :new
    end
  end

  def destroy
    @topic = Topic.friendly.find(params[:id])
    authorize @topic
    if @topic.destroy
      flash[:notice] = "\"#{@topic.title}\" was deleted successfully."
      redirect_to topics_path
    else
      flash[:error] = "There was an error deleting the topic.  Please try again."
      redirect_to @topic
    end
  end

  private
    def topic_params
      params.require(:topic).permit(:title, :user, :slug)
    end
end

app/controllers/users_controller.rb
class UsersController < ApplicationController
  def show
    @user = User.find(params[:id])
    @user_bookmarks = @user.bookmarks
    @likes = Like.where(user_id: @user.id)
    @liked_bookmarks = []
    @likes.each do |like|
      @liked_bookmarks << Bookmark.find_by(id: like.bookmark_id )
    end
    @liked_bookmarks
  end
end

app/controllers/welcome_controller.rb
class WelcomeController < ApplicationController
  def index
    redirect_to current_user if current_user
  end

  def about
  end
end

app/helpers/application_helper.rb
module ApplicationHelper

  def full_title(page_title = '')
    base_title = "Blocmarks"
    if page_title.empty?
      base_title
    else
      base_title + " | " + page_title
    end
  end
end

app/helpers/bookmarks_helper.rb
module BookmarksHelper
end

app/helpers/likes_helper.rb
module LikesHelper
end

app/helpers/topics_helper.rb
module TopicsHelper
end

app/helpers/users_helper.rb
module UsersHelper
end

app/helpers/welcome_helper.rb
module WelcomeHelper
end

app/views/bookmarks/_bookmark.html.haml
.col-md-6.small-border
  = render partial: 'likes/like', locals: { topic: bookmark.topic, bookmark: bookmark }
  - if policy(bookmark).edit?
    = link_to "Edit", edit_topic_bookmark_path(bookmark.topic, bookmark)
    = link_to "Delete", [bookmark.topic, bookmark], method: :delete, data: { confirm: 'Delete this topic for sure?' }
  <a class="embedly-card" href="#{bookmark.url}"></a><script async src="//cdn.embedly.com/widgets/platform.js" charset="UTF-8"></script>

app/views/bookmarks/_form.html.haml
= form_for [topic, bookmark] do |f|
  - if bookmark.errors.any?
    .alert.alert-danger
      %h4
        There are
        = pluralize(bookmark.errors.count, "error")
      %ul
        - bookmark.errors.full_messages.each do |msg|
          %li
            = msg
  .form-group
    = f.text_field :url, class: 'form-control' 'new-bookmark', autofocus: true, placeholder: "Enter a url to save a new bookmark.", size: 50
    &nbsp
    = f.submit "Save", class: 'btn btn-primary', onclick: "blocmetricsReport('bookmark update')"

app/views/bookmarks/edit.html.haml
- provide(:title, "Edit Bookmark")
= render partial: 'bookmarks/form', locals: { topic: @topic, bookmark: @bookmark }

app/views/bookmarks/index.html.haml
- provide(:title, "All Bookmarks")


%h1 Bookmarks

.row
  = render partial: 'bookmarks/bookmark', collection: @bookmarks

app/views/layouts/_footer.html.haml
%footer
  .footer
    %small
      The <a href="http://www.bloc.io/">Blocmarks project</a>
      by <a href="https://github.com/bgohman">Bradley Gohman</a>

app/views/layouts/_header.html.haml
%header
  .navbar.navbar-fixed-top.custom-color
    .container
      %nav
        - if current_user
          %ul
            .nav.navbar-nav.navbar-left
              %li
                = link_to "All Bookmarks", bookmarks_path
              %li
                = link_to "By Topic", topics_path    
        %ul
          .nav.navbar-nav.navbar-right
            - if current_user
              %li
                = link_to "Hello, #{current_user.name.capitalize}!", current_user
              %li
                = link_to "Settings", edit_user_registration_path(current_user)
              %li
                = link_to "Sign out", destroy_user_session_path, method: :delete
            - else
              %li
                = link_to "Sign in", new_user_session_path
              %li
                = link_to "Sign up", new_user_registration_path
            %li
              = link_to "About", about_path

app/views/layouts/application.html.erb
<!DOCTYPE html>
<html>
<head>
  <title><%= full_title(yield(:title)) %></title>
  <%= stylesheet_link_tag    'application', media: 'all', 'data-turbolinks-track' => true %>
  <%= javascript_include_tag 'application', 'data-turbolinks-track' => true %>
  <%= csrf_meta_tags %>
</head>
<body>
  
  <div class="container">
    <%= render 'layouts/header' %>
    <% flash.each do |message_type, message| %>
      <div class="alert alert-<%= message_type %>"><%= message %></div>
    <% end %>
    <%= yield %>
    <%= render 'layouts/footer' %>
    <%= debug(params) if Rails.env.development? %>
  </div>
</body>
</html>

app/views/likes/_like.html.haml
%p#demo
- if policy(Like.new).create?
  - if like = current_user.liked(bookmark)
    = link_to [topic, bookmark, like], onclick: "blocmetricsReport('unlike')", method: :delete do
      %i 
        .glyphicon.glyphicon-star

      
  - else
    = link_to [topic, bookmark, Like.new], onclick: "blocmetricsReport('like')", method: :post do
      %i 
        .glyphicon.glyphicon-star-empty

        

      

app/views/topics/_form.html.haml
= form_for [topic] do |f|
  - if topic.errors.any?
    .alert.alert-danger
      %h4 
        There are
        = pluralize(topic.errors.count, "error")
      %ul
        - topic.errors.full_messages.each do |msg|
          %li
            = msg
  = f.label :title
  = f.text_field :title, autofocus: true, class: 'form-control', placeholder: "Enter the Topic Title"
  %br
  .form-group
    = f.submit "Save", class: 'btn btn-success'

app/views/topics/edit.html.haml
- provide(:title, "Edit #{@topic.title}")
%h1 Edit #{@topic.title}
= render partial: 'form', locals: { topic: @topic }

app/views/topics/index.html.haml
- provide(:title, "Topics")

%h1 Choose a topic:

.small-border
  - @topics.each do |topic|
    %h4
      %ul
        %li
          = link_to topic.title, topic
%br
= link_to "New Topic", new_topic_path, class: 'btn btn-primary'
%br
%br

app/views/topics/new.html.haml
- provide(:title, "New Topic")
%h1  New Topic
= render partial: 'form', locals: { topic: @topic }

app/views/topics/show.html.haml
- provide(:title, "#{@topic.title}")
.container
  .row
    .col-md-6
      %h1 
        = @topic.title
    .col-md-6
      = render partial: 'bookmarks/form', locals: { topic: @topic, bookmark: @bookmark }
.container
  - if policy(@topic).edit?
    = link_to "Edit Topic", edit_topic_path
    = link_to "Delete Topic", @topic, method: :delete, data: { confirm: 'Delete this topic for sure?' }
.row  
  = render partial: 'bookmarks/bookmark', collection: @bookmarks

app/views/users/show.html.haml
- provide(:title, "My Bookmarks")
%h1 Bookmarks that I like

.row
  = render partial: 'bookmarks/bookmark', collection: @liked_bookmarks

app/views/welcome/about.html.haml
- provide(:title, "About")

%h1 About Blocmarks
%p
  It's easy enough to bookmark a URL in your browser, but eventually your bookmark library may get cluttered and it may require effort to manage bookmarks. Wouldn't you also like the ability to share bookmarks with friends? That is not something you can do easily from your native browser.
%p
  Blocmarks will solve these problems by organizing bookmarks by topic and making them public so that other users can find them and add bookmarks to their own Blocmarks profile.

app/views/welcome/index.html.haml
- provide(:title, "Home")
.center.jumbotron
  %h1 Blocmarks
  %h2
    Welcome to Blocmarks
  %p
    = link_to "Sign In", new_user_session_path, class: 'btn btn-primary'
    or
    = link_to "Sign Up", new_user_registration_path, class: 'btn btn-primary'